# escape=`

FROM lacledeslan/gamesvr-blackmesa

LABEL maintainer "Laclede's LAN <contact@lacledeslan.com>"

ENV IMAGE="gamesvr-blackmesa-freeplay"

HEALTHCHECK NONE

COPY ./dist /app/bms/

COPY ./dist.linux /app/bms/

# UPDATE USERNAME
RUN usermod -l BLACKMESAFreeplay BLACKMESA

USER BLACKMESAFreeplay

WORKDIR /app/
