# escape=`

FROM lacledeslan/gamesvr-srcds-blackmesa:linux

LABEL maintainer "Laclede's LAN <contact@lacledeslan.com>"

ENV IMAGE_NAME="gamesvr-blackmesa-freeplay:linux"

HEALTHCHECK NONE

# UPDATE USERNAME
RUN usermod -l BLACKMESAFreeplay BLACKMESA

USER BLACKMESAFreeplay

COPY ./dist /app/bin/

COPY ./dist.linux /app/bin/bms/

WORKDIR /app/bin/
